#!/usr/bin/env node
/**
 * The practice table, in the browser: the guided mana lesson walked end to
 * end with the mouse, a refusal on the way, the question at the end, then
 * reset. Everything on screen has to come from the model, so the checks
 * read the table (pool, stack, tags) rather than the coach's prose alone.
 */

import { chromium } from 'playwright'

const TARGET = process.argv[2] ?? 'http://localhost:4173/'
const SHOTS = process.env.SHOTS || null
let pass = 0
let fail = 0
const check = (label, ok, detail) => {
  if (ok) { pass++; console.log(`  PASS  ${label}`) }
  else { fail++; console.log(`  FAIL  ${label}`); if (detail) console.log(`        ${detail}`) }
}

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined })
const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
await page.route('**/api.scryfall.com/**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: '{"object":"list","data":[]}' }))
const main = () => page.locator('main').innerText()
const shot = async (name) => { if (SHOTS) await page.screenshot({ path: `${SHOTS}/${name}.png`, fullPage: true }) }

console.log('\nGetting there')
await page.goto(`${TARGET}#/practice`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
check('the practice home lists the mana lesson', /Lands, mana and a first creature/.test(await main()))
await page.getByRole('button', { name: /Cast your first creature/ }).click()
await page.waitForTimeout(500)
check('an exercise has an address', (await page.evaluate(() => location.hash)) === '#/practice/mana-guided', await page.evaluate(() => location.hash))
check('the table says whose turn, which step and who has priority', /Your turn 1 · Main phase · You have priority/.test(await main()), (await main()).match(/turn 1[^\n]*/)?.[0])
check('the stack and the pool start empty', /The stack is empty/.test(await main()) && /Mana pool\s*empty/.test(await main()))
await shot('practice-01-start')

console.log('\nMANA-01: inspecting changes nothing')
await page.getByRole('button', { name: 'Look closely at Grizzly Bears' }).click()
await page.waitForTimeout(400)
check('the viewer opens', (await page.locator('.zoom').count()) === 1)
await page.keyboard.press('Escape')
await page.waitForTimeout(300)
check('and the table is as it was', /Mana pool\s*empty/.test(await main()) && (await page.locator('.hand__card').count()) === 1)

console.log('\nThe cast')
await page.locator('.hand__card .cardface').first().click()
await page.waitForTimeout(200)
check('selecting a card in hand offers Cast without casting', (await page.getByRole('button', { name: 'Cast', exact: true }).count()) === 1 && /The stack is empty/.test(await main()))
await page.getByRole('button', { name: 'Cast', exact: true }).click()
await page.waitForTimeout(200)
check('the casting panel shows the cost with nothing paid', /Casting Grizzly Bears/.test(await main()) && /nothing in the pool: tap a source/.test(await main()))
check('the coach asks for the Forest', /Tap the Forest/.test(await main()))
await shot('practice-02-casting')
const land = (name) => page.locator(`.zone--you .permanent--land .cardface[aria-label*="${name}"], .zone--you .permanent--land .cardface`, { hasText: name }).first()
await land('Forest').click()
await page.waitForTimeout(200)
check('tapping the Forest adds one green to the pool', /1 green/.test(await main()))
check('and the Forest reads as tapped', (await page.locator('.zone--you .permanent--tapped').count()) === 1)
await land('Forest').click()
await page.waitForTimeout(200)
check('MANA-04: tapping it again is refused and the pool is unchanged', /Not allowed\.\s*Forest is already tapped/.test(await main()) && /1 green/.test(await main()) && !/2 green/.test(await main()))
await land('Mountain').click()
await page.waitForTimeout(200)
check('the Mountain adds one red', /1 green/.test(await main()) && /1 red/.test(await main()))

console.log('\nMANA-03: the wrong colour')
await page.getByRole('button', { name: 'Pay G with red mana' }).click()
await page.waitForTimeout(200)
check('red on the {G} is refused with the reason', /can only be paid with green mana/.test(await main()))
check('and nothing was committed', /1 green/.test(await main()) && /1 red/.test(await main()) && /The stack is empty/.test(await main()))
await page.getByRole('button', { name: 'Pay from pool' }).click()
await page.waitForTimeout(200)
check('paying from the pool fills both parts', (await page.locator('.cast__assigned .chip').count()) === 2 && /Paid\. Casting puts it on the stack/.test(await main()))
await shot('practice-03-paid')
await page.getByRole('button', { name: 'Cast', exact: true }).click()
await page.waitForTimeout(300)
check('MANA-02: the spell is on the stack, not the battlefield, and the mana is spent', /top\s*Grizzly Bears\s*yours/.test(await main()) && /Mana pool\s*empty/.test(await main()) && (await page.locator('.zone--you .permanent:not(.permanent--land)').count()) === 0)
check('MANA-05: one spell on the stack, one hand card gone', (await page.locator('.table__spell').count()) === 1 && /Your hand: empty/.test(await main()))
check('the coach says to pass', /Pass\. Your opponent passes too/.test(await main()))
await shot('practice-04-stack')

console.log('\nMANA-06: resolution')
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(400)
check('after both pass, Grizzly Bears is on the battlefield', (await page.locator('.zone--you .permanent:not(.permanent--land)').count()) === 1 && /The stack is empty/.test(await main()))
check('summoning sick, and the lands still tapped', (await page.locator('.zone--you .permanent--sick').count()) === 1 && (await page.locator('.zone--you .permanent--land.permanent--tapped').count()) === 2)
check('priority is back with you in the same main phase', /Your turn 1 · Main phase · You have priority/.test(await main()))
check('the first goal ticks', /✓ Grizzly Bears is on the battlefield/.test(await main()))
await shot('practice-05-resolved')

console.log('\nThe question')
check('the why-question appears', /What untaps\?/.test(await main()))
await page.getByRole('button', { name: /The mana you spent comes back/ }).click()
await page.waitForTimeout(200)
check('a wrong answer explains and the lesson is not done', /Not quite/.test(await main()) && !/Every goal is met/.test(await main()))
await page.getByRole('button', { name: 'Try again' }).click()
await page.getByRole('button', { name: /The Forest and the Mountain/ }).click()
await page.waitForTimeout(200)
check('the right answer completes the lesson', /Every goal is met/.test(await main()) && /✓ Say what untaps next turn/.test(await main()))
await shot('practice-06-done')

console.log('\nMANA-11: mana empties with the step')
await page.getByRole('button', { name: 'Reset' }).click()
await page.waitForTimeout(300)
check('MANA-08: reset restores the fixture', /Mana pool\s*empty/.test(await main()) && (await page.locator('.hand__card').count()) === 1 && (await page.locator('.zone--you .permanent--tapped').count()) === 0)
await land('Forest').click()
await page.waitForTimeout(150)
check('a source can be tapped outside a cast, with priority', /1 green/.test(await main()))
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(300)
check('passing with an empty stack moves on and empties the pool', /Beginning of combat/.test(await main()) && /Mana pool\s*empty/.test(await main()), (await main()).match(/turn 1[^\n]*/)?.[0])
check('the Forest stays tapped', (await page.locator('.zone--you .permanent--tapped').count()) === 1)
await page.getByRole('button', { name: 'Undo the last action (practice only)' }).click()
await page.waitForTimeout(200)
check('undo steps back one action', /Main phase/.test(await main()) && /1 green/.test(await main()))

console.log('\nThe wrong-colour exercise')
await page.goto(`${TARGET}#/practice/mana-wrong-colour`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
await page.locator('.hand__card .cardface', { hasText: 'Hill Giant' }).click()
await page.getByRole('button', { name: 'Cast', exact: true }).click()
for (let i = 0; i < 4; i++) { await page.locator('.zone--you .permanent--land:not(.permanent--tapped) .cardface').first().click(); await page.waitForTimeout(80) }
check('four Forests make four green', /4 green/.test(await main()))
await page.getByRole('button', { name: 'Pay from pool' }).click()
await page.waitForTimeout(200)
check('paying is refused for the colour, not the count', /short of red mana/.test(await main()))
check('and Cast stays disabled', await page.getByRole('button', { name: 'Cast', exact: true }).isDisabled())
await page.getByRole('button', { name: 'Cancel' }).click()
await page.waitForTimeout(200)
check('cancelling keeps the mana made', /4 green/.test(await main()) && !/Casting Hill Giant/.test(await main()))

console.log('\nMANA-09: a reload resumes at the last committed action')
await page.goto(`${TARGET}#/practice/mana-guided`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
await page.locator('.hand__card .cardface').first().click()
await page.getByRole('button', { name: 'Cast', exact: true }).click()
await land('Forest').click()
await land('Mountain').click()
await page.getByRole('button', { name: 'Pay from pool' }).click()
await page.getByRole('button', { name: 'Cast', exact: true }).click()
await page.waitForTimeout(300)
await page.reload({ waitUntil: 'networkidle' })
await page.waitForTimeout(600)
check('the spell is still on the stack after a reload, paid once', /top\s*Grizzly Bears\s*yours/.test(await main()) && /Mana pool\s*empty/.test(await main()) && (await page.locator('.zone--you .permanent--tapped').count()) === 2)
check('and the screen says it picked up', /Picked up where you left off/.test(await main()))
check('the journal survived too', /You cast Grizzly Bears\. It is on the stack\./.test(await main()))
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(400)
check('play continues from there', (await page.locator('.zone--you .permanent--sick').count()) === 1)
await page.goto(`${TARGET}#/practice`, { waitUntil: 'networkidle' })
await page.waitForTimeout(300)
check('the home lists the run as in progress', /Cast your first creature[^\n]*in progress/.test(await main()))
await page.goBack()
await page.waitForTimeout(500)
check('Back returns to the same exercise, still resumed', (await page.locator('.zone--you .permanent--sick').count()) === 1, await page.evaluate(() => location.hash))

console.log('\nReplay shows history without touching the game')
await page.locator('summary', { hasText: 'What happened, step by step' }).click()
await page.getByRole('button', { name: 'Step through it' }).click()
await page.waitForTimeout(200)
check('replay mode names its position', /Action \d+ of \d+ · ?/.test(await main()) || /Action \d+ of \d+/.test(await main()))
await page.getByRole('button', { name: '← Earlier' }).click()
await page.getByRole('button', { name: '← Earlier' }).click()
await page.waitForTimeout(200)
check('earlier states show the spell back on the stack', /top\s*Grizzly Bears/.test(await main()))
check('controls are gone while replaying', (await page.getByRole('button', { name: 'Pass priority' }).count()) === 0)
await page.getByRole('button', { name: 'Back to the table' }).click()
await page.waitForTimeout(200)
check('leaving replay restores the live table unchanged', (await page.locator('.zone--you .permanent--sick').count()) === 1 && /The stack is empty/.test(await main()))

console.log('\nMANA-12: paper practice is a self-report')
await page.locator('summary', { hasText: 'Now with real cards' }).click()
check('the paper prompt lists what to lay out, do and say', /You need/.test(await main()) && /Say this/.test(await main()))
await page.getByLabel('I did this with real cards').check()
await page.waitForTimeout(200)
check('it is recorded as told, not as a demonstration', /Recorded as what you told us/.test(await main()))
const practiceRecord = await page.evaluate(() => JSON.parse(localStorage.getItem('mtg-companion:v1')).practice)
check('stored under practice.paper with selfReported set', practiceRecord.paper['mana-guided']?.selfReported === true)
check('and nothing in the evidence calls it demonstrated', !practiceRecord.evidence['mana-first-creature']?.demonstrated)

console.log('\nReduced motion is the same lesson')
const still = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' })
still.on('pageerror', (e) => errors.push(e.message))
await still.route('**/api.scryfall.com/**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: '{"object":"list","data":[]}' }))
await still.goto(`${TARGET}#/practice/mana-guided`, { waitUntil: 'networkidle' })
await still.waitForTimeout(500)
await still.getByRole('button', { name: 'Reset' }).click()
await still.waitForTimeout(200)
check('the motion control reads the system setting', (await still.getByRole('button', { name: /Motion reduced/ }).count()) === 1)
await still.locator('.hand__card .cardface').first().click()
await still.getByRole('button', { name: 'Cast', exact: true }).click()
await still.locator('.zone--you .permanent--land .cardface').first().click()
await still.locator('.zone--you .permanent--land:not(.permanent--tapped) .cardface').first().click()
await still.getByRole('button', { name: 'Pay from pool' }).click()
await still.getByRole('button', { name: 'Cast', exact: true }).click()
await still.getByRole('button', { name: 'Pass priority' }).click()
await still.waitForTimeout(300)
check('with no motion the same decisions reach the same board', (await still.locator('.zone--you .permanent--sick').count()) === 1 && (await still.locator('.zone--you .permanent--land.permanent--tapped').count()) === 2)
await still.locator('summary', { hasText: 'What happened, step by step' }).click()
check('and the journal carries what motion would have shown', /Forest tapped for green/.test(await still.locator('main').innerText()) && /Grizzly Bears resolved/.test(await still.locator('main').innerText()))
check('no cue class is applied', (await still.locator('[class*="cue-"]').count()) === 0)
await still.close()

console.log('\nKeyboard only')
const kb = await browser.newPage({ viewport: { width: 390, height: 844 } })
kb.on('pageerror', (e) => errors.push(e.message))
await kb.route('**/api.scryfall.com/**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: '{"object":"list","data":[]}' }))
await kb.goto(`${TARGET}#/practice/mana-wrong-colour`, { waitUntil: 'networkidle' })
await kb.waitForTimeout(500)
const press = async (locator) => { await locator.focus(); await kb.keyboard.press('Enter'); await kb.waitForTimeout(120) }
await press(kb.locator('.hand__card .cardface', { hasText: 'Grizzly Bears' }))
await press(kb.getByRole('button', { name: 'Cast', exact: true }))
await press(kb.locator('.zone--you .permanent--land:not(.permanent--tapped) .cardface').first())
await press(kb.locator('.zone--you .permanent--land:not(.permanent--tapped) .cardface').first())
await press(kb.getByRole('button', { name: 'Pay from pool' }))
await press(kb.getByRole('button', { name: 'Cast', exact: true }))
await press(kb.getByRole('button', { name: 'Pass priority' }))
check('the cast can be completed with Enter alone', (await kb.locator('.zone--you .permanent--sick').count()) === 1)
await press(kb.getByRole('button', { name: /Its \{R\} needs red mana/ }))
check('and the question answered the same way', /Every goal is met/.test(await kb.locator('main').innerText()))
await kb.close()

console.log('\nCombat: predict, attack, block, damage')
await page.goto(`${TARGET}#/practice/combat-trade`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
await page.getByRole('button', { name: 'Reset' }).click()
await page.waitForTimeout(200)
check('the prediction is asked before anything can happen', /Before you act: Your 2\/2 Grizzly Bears attacks/.test(await main()) && await page.getByRole('button', { name: 'Pass priority' }).isDisabled())
check('the opponent\'s behaviour is written on the screen', /Practice opponent: Blocks every attacker it can/.test(await main()))
await page.getByRole('button', { name: 'Both die' }).click()
await page.waitForTimeout(200)
check('a right prediction is acknowledged and play opens', /Your prediction was right/.test(await main()) && !(await page.getByRole('button', { name: 'Pass priority' }).isDisabled()))
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(200)
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(300)
check('declare attackers waits on the learner', /Waiting on you to declare attackers/.test(await main()) && /Declare attackers/.test(await main()))
await page.locator('.zone--you .permanent:not(.permanent--land) .cardface').first().click()
await page.waitForTimeout(150)
check('choosing a creature on the table marks it', (await page.locator('.zone--you .permanent--chosen').count()) === 1)
await page.getByRole('button', { name: /Attack with 1/ }).click()
await page.waitForTimeout(300)
check('attacking taps the Bears', (await page.locator('.zone--you .permanent--attacking.permanent--tapped').count()) === 1)
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(300)
check('they block, and the blocker is not tapped', (await page.locator('.zone--foe .permanent--blocking').count()) === 1 && (await page.locator('.zone--foe .permanent--blocking.permanent--tapped').count()) === 0 && /Declare blockers/.test(await main()))
check('priority is given before damage', /You have priority/.test(await main()))
await shot('practice-08-blocked')
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(400)
check('damage is simultaneous and both die', (await page.locator('.zone--you .permanent:not(.permanent--land)').count()) === 0 && (await page.locator('.zone--foe .permanent:not(.permanent--land)').count()) === 0)
check('nobody lost life', /Opponent[\s\S]*20/.test(await main()) && /You[\s\S]*20/.test(await main()))
check('the lesson completes', /Every goal is met/.test(await main()))
check('the journal says who dealt what', /Grizzly Bears dealt 2 damage to Goblin Piker/.test(await main()) && /Goblin Piker died of lethal damage/.test(await main()))

console.log('\nReadiness: the refusal names the reason')
await page.goto(`${TARGET}#/practice/combat-readiness`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
await page.getByRole('button', { name: 'Reset' }).click()
await page.waitForTimeout(200)
await page.getByRole('button', { name: /Only Raging Goblin, because it has haste/ }).click()
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(300)
check('the panel says which creature is summoning sick', /Grizzly Bears 2\/2 · summoning sick/.test(await main()))
await page.locator('.declare').getByRole('button', { name: /Grizzly Bears 2\/2/ }).click()
await page.getByRole('button', { name: /Attack with 1/ }).click()
await page.waitForTimeout(200)
check('choosing it anyway is refused with the rule', /Not allowed\.\s*Grizzly Bears is summoning sick/.test(await main()))
await page.locator('.declare').getByRole('button', { name: /Grizzly Bears 2\/2/ }).click()
await page.locator('.declare').getByRole('button', { name: /Raging Goblin 1\/1/ }).click()
await page.getByRole('button', { name: /Attack with 1/ }).click()
await page.waitForTimeout(200)
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(200)
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(300)
check('the Goblin connects for one', /Every goal is met/.test(await main()))

console.log('\nResponses: two spells on the stack')
await page.goto(`${TARGET}#/practice/response-guided`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
await page.getByRole('button', { name: 'Reset' }).click()
await page.waitForTimeout(200)
check('their Shock is on the stack, aimed at the Bears, and it is their turn', /top\s*Shock\s*theirs · targeting Grizzly Bears/.test(await main()) && /Their turn 2/.test(await main()))
check('both predictions are asked first', /If you pass without responding/.test(await main()) && /if you cast Giant Growth/.test(await main()))
await page.getByRole('button', { name: /Shock resolves and the Bears dies/ }).click()
await page.getByRole('button', { name: /Giant Growth resolves first/ }).click()
await page.waitForTimeout(200)
await page.locator('.hand__card .cardface', { hasText: 'Giant Growth' }).click()
await page.getByRole('button', { name: 'Cast', exact: true }).click()
await page.waitForTimeout(200)
check('an instant can be cast on their turn, and asks for a target', /Choose a target: a creature on the battlefield/.test(await main()))
await page.locator('.zone--you .permanent--target .cardface').first().click()
await page.waitForTimeout(150)
check('the target is named', /Target: Grizzly Bears/.test(await main()))
await land('Forest').click()
await page.getByRole('button', { name: 'Pay from pool' }).click()
await page.getByRole('button', { name: 'Cast', exact: true }).click()
await page.waitForTimeout(300)
check('Giant Growth sits on top of the Shock', /top\s*Giant Growth\s*yours[\s\S]*2\s*Shock\s*theirs/.test(await main()))
await shot('practice-09-stack')
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(300)
check('one round of passes resolves only the top: the Bears is 5/5 and Shock still waits', /5\/5/.test(await main()) && /top\s*Shock/.test(await main()) && (await page.locator('.table__spell').count()) === 1)
await page.getByRole('button', { name: 'Pass priority' }).click()
await page.waitForTimeout(400)
check('Shock resolves into a 5/5 and the Bears lives with 2 damage', (await page.locator('.zone--you .permanent:not(.permanent--land)').count()) === 1 && /2 dmg/i.test(await main()) && /The stack is empty/.test(await main()))
check('the response lesson completes', /Every goal is met/.test(await main()))

console.log('\nThe practice home: evidence and what comes next')
await page.goto(`${TARGET}#/practice`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
check('the mana lesson shows what was earned', /Lands, mana and a first creature[\s\S]*(practiced|demonstrated)/.test(await main()))
check('completed exercises are ticked and say whether hints were used', /Cast your first creature[^\n]*done without hints/.test(await main()))
check('Continue practicing names the next exercise not yet done', /Next[\s\S]*Cast it yourself/i.test(await main()) && (await page.getByRole('button', { name: 'Continue practicing' }).count()) === 1)
check('the evidence note keeps the three kinds apart', /Viewed, practiced and demonstrated are kept apart/.test(await main()))
await page.getByRole('button', { name: 'Continue practicing' }).click()
await page.waitForTimeout(400)
check('it opens that exercise', (await page.evaluate(() => location.hash)) === '#/practice/mana-independent', await page.evaluate(() => location.hash))

console.log('\nThe colour explorer')
await page.goto(`${TARGET}#/practice/colours`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
check('five labelled controls, none pressed', (await page.locator('.explorer__toggle').count()) === 5 && (await page.locator('.explorer__toggle[aria-pressed="true"]').count()) === 0)
check('the handoff waits for a choice', await page.getByRole('button', { name: /Choose one or two colours first/ }).isDisabled())
await page.getByRole('button', { name: 'Green', exact: true }).click()
await page.waitForTimeout(150)
check('one colour opens its page, marked as the app\'s own', /Cares about[\s\S]*Growth, instinct/.test(await main()) && /this app’s own summary/.test(await main()))
check('and names a real card to open', (await page.getByRole('button', { name: 'Llanowar Elves' }).count()) === 1)
await page.getByRole('button', { name: 'White', exact: true }).click()
await page.waitForTimeout(150)
check('two colours name the pair', /Selesnya/.test(await main()) && /Go wide and go together/.test(await main()))
check('the ring shows two arcs on', (await page.locator('.explorer__arc--on').count()) === 2)
await page.getByRole('button', { name: 'Red', exact: true }).click()
await page.waitForTimeout(150)
check('three colours are allowed and said to be a real way to build', (await page.locator('.explorer__toggle[aria-pressed="true"]').count()) === 3 && /Three or more colours is a real way to build/.test(await main()))
check('but the first-deck handoff needs one or two', await page.getByRole('button', { name: /Choose one or two colours first/ }).isDisabled() && /starts from one or two colours/.test(await main()))
await page.getByRole('button', { name: 'Red', exact: true }).click()
await page.waitForTimeout(150)
await page.locator('.explorer__arc').first().click() // the ring toggles too: white off
await page.waitForTimeout(150)
check('the ring can toggle a colour without dragging', (await page.locator('.explorer__toggle[aria-pressed="true"]').count()) === 1)
await page.getByRole('button', { name: 'White', exact: true }).click()
await page.getByRole('button', { name: /Start from White and Green/ }).click()
await page.waitForTimeout(600)
check('the handoff lands on the first-deck colours step with the pair set', (await page.evaluate(() => location.hash)) === '#/decks/new/colours' && /Green and White — Selesnya/.test(await page.getByLabel('Colour dial').getAttribute('aria-valuetext') ?? ''), await page.getByLabel('Colour dial').getAttribute('aria-valuetext'))
check('and no deck was created', (await page.evaluate(() => Object.keys(localStorage).filter((k) => k.startsWith('mtg-companion:v1:deck:')).length)) === 0)

console.log('\nThe table reference')
await page.goto(`${TARGET}#/practice/reference`, { waitUntil: 'networkidle' })
await page.waitForTimeout(400)
check('every step of a turn is listed with what happens', /Untap step[\s\S]*Cleanup/.test(await main()) && /blocking does not tap/.test(await main()))
check('the zones open the glossary', (await page.locator('.reference__zones .term').count()) >= 5 || /Battlefield/.test(await main()))
check('and it says it is not a judge', /A reference, not a judge/.test(await main()))

console.log('\nWide screen')
await page.setViewportSize({ width: 1200, height: 900 })
await page.goto(`${TARGET}#/practice/mana-guided`, { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
check('the coach sits beside the board on a wide screen',
  (await page.locator('.coach').boundingBox()).x > (await page.locator('.table').boundingBox()).x + 300)
await shot('practice-07-desktop')

check('no console errors throughout', errors.length === 0, errors.join('; '))
console.log(`\n${pass} passed, ${fail} failed`)
await browser.close()
process.exit(fail ? 1 : 0)
